# -*- coding: utf-8 -*-

# self implementation generated from reading ui file 'wellSelectScreen24.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class wellSelectScreen24(QtGui.QWidget):
    def __init__(self):
        super(wellSelectScreen24, self).__init__()
        self.initUI()
        self.clearAll_button.clicked.connect(self.clearWells)
        self.selectAll_button.clicked.connect(self.selectedAllWells)

    def initUI(self):
        self.setObjectName(_fromUtf8("self"))
        self.resize(800, 480)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.setMaximumSize(QtCore.QSize(800, 480))
        self.setStyleSheet(_fromUtf8("background-color: rgb(97, 161, 243);"))
        self.layoutWidget = QtGui.QWidget(self)
        self.layoutWidget.setGeometry(QtCore.QRect(13, 14, 771, 411))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.back_button = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_button.sizePolicy().hasHeightForWidth())
        self.back_button.setSizePolicy(sizePolicy)
        self.back_button.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.back_button.setFont(font)
        self.back_button.setStyleSheet(_fromUtf8("background-color: rgb(255, 191, 88);\n"
"\n"
"\n"
"font: 75 14pt \"Roboto\";"))
        self.back_button.setObjectName(_fromUtf8("back_button"))
        self.horizontalLayout_4.addWidget(self.back_button)
        spacerItem = QtGui.QSpacerItem(650, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.line_2 = QtGui.QFrame(self.layoutWidget)
        self.line_2.setFrameShadow(QtGui.QFrame.Plain)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_9.addWidget(self.line_2)
        self.title_label = QtGui.QLabel(self.layoutWidget)
        self.title_label.setStyleSheet(_fromUtf8("font: 75 25pt \"Roboto\";"))
        self.title_label.setTextFormat(QtCore.Qt.AutoText)
        self.title_label.setObjectName(_fromUtf8("title_label"))
        self.verticalLayout_9.addWidget(self.title_label)
        self.line = QtGui.QFrame(self.layoutWidget)
        self.line.setFrameShadow(QtGui.QFrame.Plain)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_9.addWidget(self.line)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.verticalLayout_12.addLayout(self.verticalLayout_10)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_7.addItem(spacerItem1)
        self.row_A_label = QtGui.QLabel(self.layoutWidget)
        self.row_A_label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.row_A_label.setFont(font)
        self.row_A_label.setStyleSheet(_fromUtf8("font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: none;"))
        self.row_A_label.setAlignment(QtCore.Qt.AlignCenter)
        self.row_A_label.setObjectName(_fromUtf8("row_A_label"))
        self.verticalLayout_7.addWidget(self.row_A_label)
        self.row_B_label = QtGui.QLabel(self.layoutWidget)
        self.row_B_label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.row_B_label.setFont(font)
        self.row_B_label.setStyleSheet(_fromUtf8("font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: none;"))
        self.row_B_label.setAlignment(QtCore.Qt.AlignCenter)
        self.row_B_label.setObjectName(_fromUtf8("row_B_label"))
        self.verticalLayout_7.addWidget(self.row_B_label)
        self.row_C_label = QtGui.QLabel(self.layoutWidget)
        self.row_C_label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.row_C_label.setFont(font)
        self.row_C_label.setStyleSheet(_fromUtf8("font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: none;"))
        self.row_C_label.setAlignment(QtCore.Qt.AlignCenter)
        self.row_C_label.setObjectName(_fromUtf8("row_C_label"))
        self.verticalLayout_7.addWidget(self.row_C_label)
        self.row_D_label = QtGui.QLabel(self.layoutWidget)
        self.row_D_label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.row_D_label.setFont(font)
        self.row_D_label.setStyleSheet(_fromUtf8("font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: none;"))
        self.row_D_label.setAlignment(QtCore.Qt.AlignCenter)
        self.row_D_label.setObjectName(_fromUtf8("row_D_label"))
        self.verticalLayout_7.addWidget(self.row_D_label)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem2 = QtGui.QSpacerItem(2, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setSpacing(50)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.col_1_label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.col_1_label.sizePolicy().hasHeightForWidth())
        self.col_1_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.col_1_label.setFont(font)
        self.col_1_label.setStyleSheet(_fromUtf8("font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: none;"))
        self.col_1_label.setAlignment(QtCore.Qt.AlignCenter)
        self.col_1_label.setObjectName(_fromUtf8("col_1_label"))
        self.horizontalLayout_2.addWidget(self.col_1_label)
        self.col_2_label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.col_2_label.sizePolicy().hasHeightForWidth())
        self.col_2_label.setSizePolicy(sizePolicy)
        self.col_2_label.setStyleSheet(_fromUtf8("font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: none;"))
        self.col_2_label.setAlignment(QtCore.Qt.AlignCenter)
        self.col_2_label.setObjectName(_fromUtf8("col_2_label"))
        self.horizontalLayout_2.addWidget(self.col_2_label)
        self.col_3_label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.col_3_label.sizePolicy().hasHeightForWidth())
        self.col_3_label.setSizePolicy(sizePolicy)
        self.col_3_label.setStyleSheet(_fromUtf8("font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: none;"))
        self.col_3_label.setAlignment(QtCore.Qt.AlignCenter)
        self.col_3_label.setObjectName(_fromUtf8("col_3_label"))
        self.horizontalLayout_2.addWidget(self.col_3_label)
        self.col_4_label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.col_4_label.sizePolicy().hasHeightForWidth())
        self.col_4_label.setSizePolicy(sizePolicy)
        self.col_4_label.setStyleSheet(_fromUtf8("font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: none;"))
        self.col_4_label.setAlignment(QtCore.Qt.AlignCenter)
        self.col_4_label.setObjectName(_fromUtf8("col_4_label"))
        self.horizontalLayout_2.addWidget(self.col_4_label)
        self.col_5_label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.col_5_label.sizePolicy().hasHeightForWidth())
        self.col_5_label.setSizePolicy(sizePolicy)
        self.col_5_label.setStyleSheet(_fromUtf8("font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: none;"))
        self.col_5_label.setAlignment(QtCore.Qt.AlignCenter)
        self.col_5_label.setObjectName(_fromUtf8("col_5_label"))
        self.horizontalLayout_2.addWidget(self.col_5_label)
        self.col_6_label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.col_6_label.sizePolicy().hasHeightForWidth())
        self.col_6_label.setSizePolicy(sizePolicy)
        self.col_6_label.setStyleSheet(_fromUtf8("font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: none;"))
        self.col_6_label.setAlignment(QtCore.Qt.AlignCenter)
        self.col_6_label.setObjectName(_fromUtf8("col_6_label"))
        self.horizontalLayout_2.addWidget(self.col_6_label)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_11.addLayout(self.horizontalLayout_3)
        self.well_widget = QtGui.QWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.well_widget.sizePolicy().hasHeightForWidth())
        self.well_widget.setSizePolicy(sizePolicy)
        self.well_widget.setMinimumSize(QtCore.QSize(400, 240))
        self.well_widget.setMaximumSize(QtCore.QSize(400, 240))
        self.well_widget.setStyleSheet(_fromUtf8("background-color: rgb(0,0,0);\n"
""))
        self.well_widget.setObjectName(_fromUtf8("well_widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.well_widget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.well_A1 = QtGui.QLabel(self.well_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.well_A1.sizePolicy().hasHeightForWidth())
        self.well_A1.setSizePolicy(sizePolicy)
        self.well_A1.setMaximumSize(QtCore.QSize(60, 60))
        self.well_A1.setStyleSheet(_fromUtf8("background-color: none;"))
        self.well_A1.setText(_fromUtf8(""))
        self.well_A1.setPixmap(QtGui.QPixmap(_fromUtf8("../Python Files/Images/emptyWell_Icon.svg")))
        self.well_A1.setScaledContents(True)
        self.well_A1.setObjectName(_fromUtf8("well_A1"))
        self.verticalLayout_6.addWidget(self.well_A1)
        self.well_B1 = QtGui.QLabel(self.well_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.well_B1.sizePolicy().hasHeightForWidth())
        self.well_B1.setSizePolicy(sizePolicy)
        self.well_B1.setMaximumSize(QtCore.QSize(60, 60))
        self.well_B1.setStyleSheet(_fromUtf8("background-color: none;"))
        self.well_B1.setText(_fromUtf8(""))
        self.well_B1.setPixmap(QtGui.QPixmap(_fromUtf8("../Python Files/Images/emptyWell_Icon.svg")))
        self.well_B1.setScaledContents(True)
        self.well_B1.setObjectName(_fromUtf8("well_B1"))
        self.verticalLayout_6.addWidget(self.well_B1)
        self.well_C1 = QtGui.QLabel(self.well_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.well_C1.sizePolicy().hasHeightForWidth())
        self.well_C1.setSizePolicy(sizePolicy)
        self.well_C1.setMaximumSize(QtCore.QSize(60, 60))
        self.well_C1.setStyleSheet(_fromUtf8("background-color: none;"))
        self.well_C1.setText(_fromUtf8(""))
        self.well_C1.setPixmap(QtGui.QPixmap(_fromUtf8("../Python Files/Images/emptyWell_Icon.svg")))
        self.well_C1.setScaledContents(True)
        self.well_C1.setObjectName(_fromUtf8("well_C1"))
        self.verticalLayout_6.addWidget(self.well_C1)
        self.well_D1 = QtGui.QLabel(self.well_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.well_D1.sizePolicy().hasHeightForWidth())
        self.well_D1.setSizePolicy(sizePolicy)
        self.well_D1.setMaximumSize(QtCore.QSize(60, 60))
        self.well_D1.setStyleSheet(_fromUtf8("background-color: none;"))
        self.well_D1.setText(_fromUtf8(""))
        self.well_D1.setPixmap(QtGui.QPixmap(_fromUtf8("../Python Files/Images/emptyWell_Icon.svg")))
        self.well_D1.setScaledContents(True)
        self.well_D1.setObjectName(_fromUtf8("well_D1"))
        self.verticalLayout_6.addWidget(self.well_D1)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.well_A2 = QtGui.QLabel(self.well_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.well_A2.sizePolicy().hasHeightForWidth())
        self.well_A2.setSizePolicy(sizePolicy)
        self.well_A2.setMaximumSize(QtCore.QSize(60, 60))
        self.well_A2.setStyleSheet(_fromUtf8("background-color: none;"))
        self.well_A2.setText(_fromUtf8(""))
        self.well_A2.setPixmap(QtGui.QPixmap(_fromUtf8("../Python Files/Images/emptyWell_Icon.svg")))
        self.well_A2.setScaledContents(True)
        self.well_A2.setObjectName(_fromUtf8("well_A2"))
        self.verticalLayout_5.addWidget(self.well_A2)
        self.well_B2 = QtGui.QLabel(self.well_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.well_B2.sizePolicy().hasHeightForWidth())
        self.well_B2.setSizePolicy(sizePolicy)
        self.well_B2.setMaximumSize(QtCore.QSize(60, 60))
        self.well_B2.setStyleSheet(_fromUtf8("background-color: none;"))
        self.well_B2.setText(_fromUtf8(""))
        self.well_B2.setPixmap(QtGui.QPixmap(_fromUtf8("../Python Files/Images/emptyWell_Icon.svg")))
        self.well_B2.setScaledContents(True)
        self.well_B2.setObjectName(_fromUtf8("well_B2"))
        self.verticalLayout_5.addWidget(self.well_B2)
        self.well_C2 = QtGui.QLabel(self.well_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.well_C2.sizePolicy().hasHeightForWidth())
        self.well_C2.setSizePolicy(sizePolicy)
        self.well_C2.setMaximumSize(QtCore.QSize(60, 60))
        self.well_C2.setStyleSheet(_fromUtf8("background-color: none;"))
        self.well_C2.setText(_fromUtf8(""))
        self.well_C2.setPixmap(QtGui.QPixmap(_fromUtf8("../Python Files/Images/emptyWell_Icon.svg")))
        self.well_C2.setScaledContents(True)
        self.well_C2.setObjectName(_fromUtf8("well_C2"))
        self.verticalLayout_5.addWidget(self.well_C2)
        self.well_D2 = QtGui.QLabel(self.well_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.well_D2.sizePolicy().hasHeightForWidth())
        self.well_D2.setSizePolicy(sizePolicy)
        self.well_D2.setMaximumSize(QtCore.QSize(60, 60))
        self.well_D2.setStyleSheet(_fromUtf8("background-color: none;"))
        self.well_D2.setText(_fromUtf8(""))
        self.well_D2.setPixmap(QtGui.QPixmap(_fromUtf8("../Python Files/Images/emptyWell_Icon.svg")))
        self.well_D2.setScaledContents(True)
        self.well_D2.setObjectName(_fromUtf8("well_D2"))
        self.verticalLayout_5.addWidget(self.well_D2)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.well_A3 = QtGui.QLabel(self.well_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.well_A3.sizePolicy().hasHeightForWidth())
        self.well_A3.setSizePolicy(sizePolicy)
        self.well_A3.setMaximumSize(QtCore.QSize(60, 60))
        self.well_A3.setStyleSheet(_fromUtf8("background-color: none;"))
        self.well_A3.setText(_fromUtf8(""))
        self.well_A3.setPixmap(QtGui.QPixmap(_fromUtf8("../Python Files/Images/emptyWell_Icon.svg")))
        self.well_A3.setScaledContents(True)
        self.well_A3.setObjectName(_fromUtf8("well_A3"))
        self.verticalLayout_4.addWidget(self.well_A3)
        self.well_B3 = QtGui.QLabel(self.well_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.well_B3.sizePolicy().hasHeightForWidth())
        self.well_B3.setSizePolicy(sizePolicy)
        self.well_B3.setMaximumSize(QtCore.QSize(60, 60))
        self.well_B3.setStyleSheet(_fromUtf8("background-color: none;"))
        self.well_B3.setText(_fromUtf8(""))
        self.well_B3.setPixmap(QtGui.QPixmap(_fromUtf8("../Python Files/Images/emptyWell_Icon.svg")))
        self.well_B3.setScaledContents(True)
        self.well_B3.setObjectName(_fromUtf8("well_B3"))
        self.verticalLayout_4.addWidget(self.well_B3)
        self.well_C3 = QtGui.QLabel(self.well_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.well_C3.sizePolicy().hasHeightForWidth())
        self.well_C3.setSizePolicy(sizePolicy)
        self.well_C3.setMaximumSize(QtCore.QSize(60, 60))
        self.well_C3.setStyleSheet(_fromUtf8("background-color: none;"))
        self.well_C3.setText(_fromUtf8(""))
        self.well_C3.setPixmap(QtGui.QPixmap(_fromUtf8("../Python Files/Images/emptyWell_Icon.svg")))
        self.well_C3.setScaledContents(True)
        self.well_C3.setObjectName(_fromUtf8("well_C3"))
        self.verticalLayout_4.addWidget(self.well_C3)
        self.well_D3 = QtGui.QLabel(self.well_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.well_D3.sizePolicy().hasHeightForWidth())
        self.well_D3.setSizePolicy(sizePolicy)
        self.well_D3.setMaximumSize(QtCore.QSize(60, 60))
        self.well_D3.setStyleSheet(_fromUtf8("background-color: none;"))
        self.well_D3.setText(_fromUtf8(""))
        self.well_D3.setPixmap(QtGui.QPixmap(_fromUtf8("../Python Files/Images/emptyWell_Icon.svg")))
        self.well_D3.setScaledContents(True)
        self.well_D3.setObjectName(_fromUtf8("well_D3"))
        self.verticalLayout_4.addWidget(self.well_D3)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.well_A4 = QtGui.QLabel(self.well_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.well_A4.sizePolicy().hasHeightForWidth())
        self.well_A4.setSizePolicy(sizePolicy)
        self.well_A4.setMaximumSize(QtCore.QSize(60, 60))
        self.well_A4.setStyleSheet(_fromUtf8("background-color: none;"))
        self.well_A4.setText(_fromUtf8(""))
        self.well_A4.setPixmap(QtGui.QPixmap(_fromUtf8("../Python Files/Images/emptyWell_Icon.svg")))
        self.well_A4.setScaledContents(True)
        self.well_A4.setObjectName(_fromUtf8("well_A4"))
        self.verticalLayout_3.addWidget(self.well_A4)
        self.well_B4 = QtGui.QLabel(self.well_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.well_B4.sizePolicy().hasHeightForWidth())
        self.well_B4.setSizePolicy(sizePolicy)
        self.well_B4.setMaximumSize(QtCore.QSize(60, 60))
        self.well_B4.setStyleSheet(_fromUtf8("background-color: none;"))
        self.well_B4.setText(_fromUtf8(""))
        self.well_B4.setPixmap(QtGui.QPixmap(_fromUtf8("../Python Files/Images/emptyWell_Icon.svg")))
        self.well_B4.setScaledContents(True)
        self.well_B4.setObjectName(_fromUtf8("well_B4"))
        self.verticalLayout_3.addWidget(self.well_B4)
        self.well_C4 = QtGui.QLabel(self.well_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.well_C4.sizePolicy().hasHeightForWidth())
        self.well_C4.setSizePolicy(sizePolicy)
        self.well_C4.setMaximumSize(QtCore.QSize(60, 60))
        self.well_C4.setStyleSheet(_fromUtf8("background-color: none;"))
        self.well_C4.setText(_fromUtf8(""))
        self.well_C4.setPixmap(QtGui.QPixmap(_fromUtf8("../Python Files/Images/emptyWell_Icon.svg")))
        self.well_C4.setScaledContents(True)
        self.well_C4.setObjectName(_fromUtf8("well_C4"))
        self.verticalLayout_3.addWidget(self.well_C4)
        self.well_D4 = QtGui.QLabel(self.well_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.well_D4.sizePolicy().hasHeightForWidth())
        self.well_D4.setSizePolicy(sizePolicy)
        self.well_D4.setMaximumSize(QtCore.QSize(60, 60))
        self.well_D4.setStyleSheet(_fromUtf8("background-color: none;"))
        self.well_D4.setText(_fromUtf8(""))
        self.well_D4.setPixmap(QtGui.QPixmap(_fromUtf8("../Python Files/Images/emptyWell_Icon.svg")))
        self.well_D4.setScaledContents(True)
        self.well_D4.setObjectName(_fromUtf8("well_D4"))
        self.verticalLayout_3.addWidget(self.well_D4)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.well_A5 = QtGui.QLabel(self.well_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.well_A5.sizePolicy().hasHeightForWidth())
        self.well_A5.setSizePolicy(sizePolicy)
        self.well_A5.setMaximumSize(QtCore.QSize(60, 60))
        self.well_A5.setStyleSheet(_fromUtf8("background-color: none;"))
        self.well_A5.setText(_fromUtf8(""))
        self.well_A5.setPixmap(QtGui.QPixmap(_fromUtf8("../Python Files/Images/emptyWell_Icon.svg")))
        self.well_A5.setScaledContents(True)
        self.well_A5.setObjectName(_fromUtf8("well_A5"))
        self.verticalLayout.addWidget(self.well_A5)
        self.well_B5 = QtGui.QLabel(self.well_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.well_B5.sizePolicy().hasHeightForWidth())
        self.well_B5.setSizePolicy(sizePolicy)
        self.well_B5.setMaximumSize(QtCore.QSize(60, 60))
        self.well_B5.setStyleSheet(_fromUtf8("background-color: none;"))
        self.well_B5.setText(_fromUtf8(""))
        self.well_B5.setPixmap(QtGui.QPixmap(_fromUtf8("../Python Files/Images/emptyWell_Icon.svg")))
        self.well_B5.setScaledContents(True)
        self.well_B5.setObjectName(_fromUtf8("well_B5"))
        self.verticalLayout.addWidget(self.well_B5)
        self.well_C5 = QtGui.QLabel(self.well_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.well_C5.sizePolicy().hasHeightForWidth())
        self.well_C5.setSizePolicy(sizePolicy)
        self.well_C5.setMaximumSize(QtCore.QSize(60, 60))
        self.well_C5.setStyleSheet(_fromUtf8("background-color: none;"))
        self.well_C5.setText(_fromUtf8(""))
        self.well_C5.setPixmap(QtGui.QPixmap(_fromUtf8("../Python Files/Images/emptyWell_Icon.svg")))
        self.well_C5.setScaledContents(True)
        self.well_C5.setObjectName(_fromUtf8("well_C5"))
        self.verticalLayout.addWidget(self.well_C5)
        self.well_D5 = QtGui.QLabel(self.well_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.well_D5.sizePolicy().hasHeightForWidth())
        self.well_D5.setSizePolicy(sizePolicy)
        self.well_D5.setMaximumSize(QtCore.QSize(60, 60))
        self.well_D5.setStyleSheet(_fromUtf8("background-color: none;"))
        self.well_D5.setText(_fromUtf8(""))
        self.well_D5.setPixmap(QtGui.QPixmap(_fromUtf8("../Python Files/Images/emptyWell_Icon.svg")))
        self.well_D5.setScaledContents(True)
        self.well_D5.setObjectName(_fromUtf8("well_D5"))
        self.verticalLayout.addWidget(self.well_D5)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.well_A6 = QtGui.QLabel(self.well_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.well_A6.sizePolicy().hasHeightForWidth())
        self.well_A6.setSizePolicy(sizePolicy)
        self.well_A6.setMaximumSize(QtCore.QSize(60, 60))
        self.well_A6.setStyleSheet(_fromUtf8("background-color: none;"))
        self.well_A6.setText(_fromUtf8(""))
        self.well_A6.setPixmap(QtGui.QPixmap(_fromUtf8("../Python Files/Images/emptyWell_Icon.svg")))
        self.well_A6.setScaledContents(True)
        self.well_A6.setObjectName(_fromUtf8("well_A6"))
        self.verticalLayout_2.addWidget(self.well_A6)
        self.well_B6 = QtGui.QLabel(self.well_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.well_B6.sizePolicy().hasHeightForWidth())
        self.well_B6.setSizePolicy(sizePolicy)
        self.well_B6.setMaximumSize(QtCore.QSize(60, 60))
        self.well_B6.setStyleSheet(_fromUtf8("background-color: none;"))
        self.well_B6.setText(_fromUtf8(""))
        self.well_B6.setPixmap(QtGui.QPixmap(_fromUtf8("../Python Files/Images/emptyWell_Icon.svg")))
        self.well_B6.setScaledContents(True)
        self.well_B6.setObjectName(_fromUtf8("well_B6"))
        self.verticalLayout_2.addWidget(self.well_B6)
        self.well_C6 = QtGui.QLabel(self.well_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.well_C6.sizePolicy().hasHeightForWidth())
        self.well_C6.setSizePolicy(sizePolicy)
        self.well_C6.setMaximumSize(QtCore.QSize(60, 60))
        self.well_C6.setStyleSheet(_fromUtf8("background-color: none;"))
        self.well_C6.setText(_fromUtf8(""))
        self.well_C6.setPixmap(QtGui.QPixmap(_fromUtf8("../Python Files/Images/emptyWell_Icon.svg")))
        self.well_C6.setScaledContents(True)
        self.well_C6.setObjectName(_fromUtf8("well_C6"))
        self.verticalLayout_2.addWidget(self.well_C6)
        self.well_D6 = QtGui.QLabel(self.well_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.well_D6.sizePolicy().hasHeightForWidth())
        self.well_D6.setSizePolicy(sizePolicy)
        self.well_D6.setMaximumSize(QtCore.QSize(60, 60))
        self.well_D6.setStyleSheet(_fromUtf8("background-color: none;"))
        self.well_D6.setText(_fromUtf8(""))
        self.well_D6.setPixmap(QtGui.QPixmap(_fromUtf8("../Python Files/Images/emptyWell_Icon.svg")))
        self.well_D6.setScaledContents(True)
        self.well_D6.setObjectName(_fromUtf8("well_D6"))
        self.verticalLayout_2.addWidget(self.well_D6)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_11.addWidget(self.well_widget)
        self.horizontalLayout_5.addLayout(self.verticalLayout_11)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.selectAll_button = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectAll_button.sizePolicy().hasHeightForWidth())
        self.selectAll_button.setSizePolicy(sizePolicy)
        self.selectAll_button.setMinimumSize(QtCore.QSize(150, 48))
        self.selectAll_button.setMaximumSize(QtCore.QSize(250, 35))
        self.selectAll_button.setStyleSheet(_fromUtf8("background-color: rgb(255, 191, 88);\n"
"\n"
"\n"
"font: 75 20pt \"Roboto\";"))
        self.selectAll_button.setObjectName(_fromUtf8("selectAll_button"))
        self.verticalLayout_8.addWidget(self.selectAll_button)
        self.clearAll_button = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearAll_button.sizePolicy().hasHeightForWidth())
        self.clearAll_button.setSizePolicy(sizePolicy)
        self.clearAll_button.setMinimumSize(QtCore.QSize(150, 50))
        self.clearAll_button.setMaximumSize(QtCore.QSize(250, 35))
        self.clearAll_button.setStyleSheet(_fromUtf8("background-color: rgb(255, 191, 88);\n"
"\n"
"\n"
"font: 75 20pt \"Roboto\";"))
        self.clearAll_button.setObjectName(_fromUtf8("clearAll_button"))
        self.verticalLayout_8.addWidget(self.clearAll_button)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_8.addItem(spacerItem4)
        self.ready_button = QtGui.QPushButton(self.layoutWidget)
        self.ready_button.setMinimumSize(QtCore.QSize(150, 50))
        self.ready_button.setMaximumSize(QtCore.QSize(250, 35))
        self.ready_button.setStyleSheet(_fromUtf8("background-color: rgb(255, 191, 88);\n"
"\n"
"\n"
"font: 75 20pt \"Roboto\";"))
        self.ready_button.setObjectName(_fromUtf8("ready_button"))
        self.verticalLayout_8.addWidget(self.ready_button)
        self.horizontalLayout_6.addLayout(self.verticalLayout_8)
        self.verticalLayout_12.addLayout(self.horizontalLayout_6)

        rows = ['A', 'B', 'C', 'D']
        self.names = []
        self.status = []
        self.wellNames = []
        for row in rows[0:4]:
            for column in range(0, 6):
                self.wellNames.append('well_' + row + str(column + 1))
                self.names.append(row + str(column + 1))
                self.status.append('OFF')

        self.rubberband = QtGui.QRubberBand(
            QtGui.QRubberBand.Rectangle, self)

        self.well_widget.setMouseTracking(True)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

        self.show()

    def mousePressEvent(self, event):
        self.origin = event.pos()
        self.relativePos = event.pos() - self.well_widget.pos()

        for child in self.well_widget.findChildren(QtGui.QLabel):
            rect_correct = QtCore.QRect(child.pos().x(), child.pos().y(),
                                        int(str(child.geometry().width())) - 10,
                                        int(str(child.geometry().height())) - 10)
            if rect_correct.contains(self.relativePos):
                if str(child.objectName()) in self.wellNames:
                    name = str(child.objectName())
                    label = name[5:len(name)]
                    row = name[5]
                    column = int(name[6:len(name)])
                    if self.status[self.names.index(label)] == 'OFF':
                        child.setPixmap(QtGui.QPixmap(_fromUtf8("Images/selectedWell_Icon.png")))
                        self.status[self.names.index(label)] = 'ON'
                    elif self.status[self.names.index(label)] == 'ON':
                        child.setPixmap(QtGui.QPixmap(_fromUtf8("Images/emptyWell_Icon.svg")))
                        self.status[self.names.index(label)] = 'OFF'
        self.rubberband.setGeometry(
            QtCore.QRect(self.origin, QtCore.QSize()))
        self.rubberband.show()
        QtGui.QWidget.mousePressEvent(self, event)

    def mouseMoveEvent(self, event):
        if self.rubberband.isVisible():
            self.rubberband.setGeometry(
                QtCore.QRect(self.origin, event.pos()).normalized())
        QtGui.QWidget.mouseMoveEvent(self, event)

    def mouseReleaseEvent(self, event):
        if self.rubberband.isVisible():
            self.rubberband.hide()
            rect = self.rubberband.geometry()
            rect_correct = QtCore.QRect(rect.x() - self.well_widget.pos().x(), rect.y() - self.well_widget.pos().y(),
                                        int(str(rect.width())) - 10,
                                        int(str(rect.height())) - 10)
            for child in self.findChildren(QtGui.QLabel):
                if rect_correct.intersects(child.geometry()):
                    if str(child.objectName()) in self.wellNames:
                        name = str(child.objectName())
                        label = name[5:len(name)]
                        row = name[5]
                        column = int(name[6:len(name)])
                        if self.status[self.names.index(label)] == 'OFF':
                            child.setPixmap(QtGui.QPixmap(_fromUtf8("Images/selectedWell_Icon.png")))
                            self.status[self.names.index(label)] = 'ON'
                        elif self.status[self.names.index(label)] == 'ON':
                            child.setPixmap(QtGui.QPixmap(_fromUtf8("Images/emptyWell_Icon.svg")))
                            self.status[self.names.index(label)] = 'OFF'

        QtGui.QWidget.mouseReleaseEvent(self, event)

    def clearWells(self):
        for child in self.findChildren(QtGui.QLabel):
            if str(child.objectName()) in self.wellNames:
                name = str(child.objectName())
                label = name[5:len(name)]
                row = name[5]
                column = int(name[6:len(name)])
                child.setPixmap(QtGui.QPixmap(_fromUtf8("Images/emptyWell_Icon.svg")))
                self.status[self.names.index(label)] = 'OFF'

    def selectedAllWells(self):
        for child in self.findChildren(QtGui.QLabel):
            if str(child.objectName()) in self.wellNames:
                name = str(child.objectName())
                label = name[5:len(name)]
                row = name[5]
                column = int(name[6:len(name)])
                child.setPixmap(QtGui.QPixmap(_fromUtf8("Images/selectedWell_Icon.png")))
                self.status[self.names.index(label)] = 'ON'

    def retranslateUi(self):
        self.setWindowTitle(_translate("self", "OSP", None))
        self.setWindowIcon(QtGui.QIcon("../Python Files/Images/logo_icon.png"))
        self.back_button.setText(_translate("self", "Back", None))
        self.title_label.setText(_translate("self", "<html><head/><body><p align=\"center\">SELECT WELLS</p></body></html>", None))
        self.row_A_label.setText(_translate("self", "A", None))
        self.row_B_label.setText(_translate("self", "B", None))
        self.row_C_label.setText(_translate("self", "C", None))
        self.row_D_label.setText(_translate("self", "D", None))
        self.col_1_label.setText(_translate("self", "1", None))
        self.col_2_label.setText(_translate("self", "2", None))
        self.col_3_label.setText(_translate("self", "3", None))
        self.col_4_label.setText(_translate("self", "4", None))
        self.col_5_label.setText(_translate("self", "5", None))
        self.col_6_label.setText(_translate("self", "6", None))
        self.selectAll_button.setText(_translate("self", "Select All", None))
        self.clearAll_button.setText(_translate("self", "Clear All", None))
        self.ready_button.setText(_translate("self", "READY", None))

