# -*- coding: utf-8 -*-

# self implementation generated from reading ui file 'auxScreen.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class auxScreen(QtGui.QWidget):
    def __init__(self):
        super(auxScreen, self).__init__()
        self.initUI()
        self.ischecked = 0
        self.ctrl1_checkBox.stateChanged.connect(lambda: self.change_ctrl(1))
        self.ctrl2_checkBox.stateChanged.connect(lambda: self.change_ctrl(2))
        self.ctrl3_checkBox.stateChanged.connect(lambda: self.change_ctrl(3))
        self.aux_led_checkBox.stateChanged.connect(lambda: self.change_ctrl(4))


    def initUI(self):
        self.setObjectName(_fromUtf8("self"))
        self.resize(800, 480)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.setMaximumSize(QtCore.QSize(800, 480))
        self.setStyleSheet(_fromUtf8("background-color: rgb(97, 161, 243);"))
        self.layoutWidget = QtGui.QWidget(self)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 11, 787, 401))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.back_button = QtGui.QPushButton(self.layoutWidget)
        self.back_button.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.back_button.setFont(font)
        self.back_button.setStyleSheet(_fromUtf8("background-color: rgb(255, 191, 88);"))
        self.back_button.setObjectName(_fromUtf8("back_button"))
        self.horizontalLayout_17.addWidget(self.back_button)
        spacerItem = QtGui.QSpacerItem(675, 35, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.line_7 = QtGui.QFrame(self.layoutWidget)
        self.line_7.setFrameShadow(QtGui.QFrame.Plain)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.verticalLayout_10.addWidget(self.line_7)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem1 = QtGui.QSpacerItem(88, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.title_label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_label.sizePolicy().hasHeightForWidth())
        self.title_label.setSizePolicy(sizePolicy)
        self.title_label.setMaximumSize(QtCore.QSize(555, 40))
        self.title_label.setStyleSheet(_fromUtf8("font: 75 25pt \"Roboto\";"))
        self.title_label.setTextFormat(QtCore.Qt.AutoText)
        self.title_label.setObjectName(_fromUtf8("title_label"))
        self.horizontalLayout_4.addWidget(self.title_label)
        spacerItem2 = QtGui.QSpacerItem(88, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        self.line_8 = QtGui.QFrame(self.layoutWidget)
        self.line_8.setFrameShadow(QtGui.QFrame.Plain)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.verticalLayout_10.addWidget(self.line_8)
        self.verticalLayout.addLayout(self.verticalLayout_10)
        spacerItem3 = QtGui.QSpacerItem(20, 90, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.aux_led_checkBox = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.aux_led_checkBox.setFont(font)
        self.aux_led_checkBox.setStyleSheet(_fromUtf8("QCheckBox::indicator {\n"
"width: 30px;\n"
" height: 30px;}"))
        self.aux_led_checkBox.setIconSize(QtCore.QSize(50, 50))
        self.aux_led_checkBox.setCheckable(True)
        self.aux_led_checkBox.setObjectName(_fromUtf8("aux_led_checkBox"))
        self.horizontalLayout_18.addWidget(self.aux_led_checkBox)
        spacerItem4 = QtGui.QSpacerItem(72, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem4)
        self.line_15 = QtGui.QFrame(self.layoutWidget)
        self.line_15.setFrameShadow(QtGui.QFrame.Plain)
        self.line_15.setFrameShape(QtGui.QFrame.VLine)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.horizontalLayout_18.addWidget(self.line_15)
        self.ctrl1_checkBox = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ctrl1_checkBox.setFont(font)
        self.ctrl1_checkBox.setStyleSheet(_fromUtf8("QCheckBox::indicator {\n"
"width: 30px;\n"
" height: 30px;}"))
        self.ctrl1_checkBox.setIconSize(QtCore.QSize(50, 50))
        self.ctrl1_checkBox.setCheckable(True)
        self.ctrl1_checkBox.setObjectName(_fromUtf8("ctrl1_checkBox"))
        self.horizontalLayout_18.addWidget(self.ctrl1_checkBox)
        spacerItem5 = QtGui.QSpacerItem(79, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem5)
        self.line_11 = QtGui.QFrame(self.layoutWidget)
        self.line_11.setFrameShadow(QtGui.QFrame.Plain)
        self.line_11.setFrameShape(QtGui.QFrame.VLine)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.horizontalLayout_18.addWidget(self.line_11)
        self.ctrl2_checkBox = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ctrl2_checkBox.setFont(font)
        self.ctrl2_checkBox.setStyleSheet(_fromUtf8("QCheckBox::indicator {\n"
"width: 30px;\n"
" height: 30px;}"))
        self.ctrl2_checkBox.setIconSize(QtCore.QSize(50, 50))
        self.ctrl2_checkBox.setCheckable(True)
        self.ctrl2_checkBox.setObjectName(_fromUtf8("ctrl2_checkBox"))
        self.horizontalLayout_18.addWidget(self.ctrl2_checkBox)
        spacerItem6 = QtGui.QSpacerItem(67, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem6)
        self.line_12 = QtGui.QFrame(self.layoutWidget)
        self.line_12.setFrameShadow(QtGui.QFrame.Plain)
        self.line_12.setFrameShape(QtGui.QFrame.VLine)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.horizontalLayout_18.addWidget(self.line_12)
        self.ctrl3_checkBox = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ctrl3_checkBox.setFont(font)
        self.ctrl3_checkBox.setStyleSheet(_fromUtf8("QCheckBox::indicator {\n"
"width: 30px;\n"
" height: 30px;}"))
        self.ctrl3_checkBox.setIconSize(QtCore.QSize(50, 50))
        self.ctrl3_checkBox.setCheckable(True)
        self.ctrl3_checkBox.setObjectName(_fromUtf8("ctrl3_checkBox"))
        self.horizontalLayout_18.addWidget(self.ctrl3_checkBox)
        spacerItem7 = QtGui.QSpacerItem(65, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_18)
        spacerItem8 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem8)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.duration_AL_label = QtGui.QLabel(self.layoutWidget)
        self.duration_AL_label.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.duration_AL_label.sizePolicy().hasHeightForWidth())
        self.duration_AL_label.setSizePolicy(sizePolicy)
        self.duration_AL_label.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.duration_AL_label.setFont(font)
        self.duration_AL_label.setAlignment(QtCore.Qt.AlignCenter)
        self.duration_AL_label.setObjectName(_fromUtf8("duration_AL_label"))
        self.horizontalLayout_21.addWidget(self.duration_AL_label)
        self.duration_AL_spinBox = QtGui.QSpinBox(self.layoutWidget)
        self.duration_AL_spinBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.duration_AL_spinBox.sizePolicy().hasHeightForWidth())
        self.duration_AL_spinBox.setSizePolicy(sizePolicy)
        self.duration_AL_spinBox.setMinimumSize(QtCore.QSize(100, 35))
        self.duration_AL_spinBox.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.duration_AL_spinBox.setFont(font)
        self.duration_AL_spinBox.setStyleSheet(_fromUtf8("background-color: rgb(255,255,255);"))
        self.duration_AL_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.duration_AL_spinBox.setPrefix(_fromUtf8(""))
        self.duration_AL_spinBox.setMinimum(1)
        self.duration_AL_spinBox.setMaximum(10000000)
        self.duration_AL_spinBox.setProperty("value", 1)
        self.duration_AL_spinBox.setObjectName(_fromUtf8("duration_AL_spinBox"))
        self.horizontalLayout_21.addWidget(self.duration_AL_spinBox)
        spacerItem9 = QtGui.QSpacerItem(90, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem9)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_21)
        self.line_14 = QtGui.QFrame(self.layoutWidget)
        self.line_14.setFrameShadow(QtGui.QFrame.Plain)
        self.line_14.setFrameShape(QtGui.QFrame.VLine)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.horizontalLayout_20.addWidget(self.line_14)
        self.duration_C1_label = QtGui.QLabel(self.layoutWidget)
        self.duration_C1_label.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.duration_C1_label.sizePolicy().hasHeightForWidth())
        self.duration_C1_label.setSizePolicy(sizePolicy)
        self.duration_C1_label.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.duration_C1_label.setFont(font)
        self.duration_C1_label.setAlignment(QtCore.Qt.AlignCenter)
        self.duration_C1_label.setObjectName(_fromUtf8("duration_C1_label"))
        self.horizontalLayout_20.addWidget(self.duration_C1_label)
        self.duration_C1_spinBox = QtGui.QSpinBox(self.layoutWidget)
        self.duration_C1_spinBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.duration_C1_spinBox.sizePolicy().hasHeightForWidth())
        self.duration_C1_spinBox.setSizePolicy(sizePolicy)
        self.duration_C1_spinBox.setMinimumSize(QtCore.QSize(100, 35))
        self.duration_C1_spinBox.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.duration_C1_spinBox.setFont(font)
        self.duration_C1_spinBox.setStyleSheet(_fromUtf8("background-color: rgb(255,255,255);"))
        self.duration_C1_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.duration_C1_spinBox.setPrefix(_fromUtf8(""))
        self.duration_C1_spinBox.setMinimum(1)
        self.duration_C1_spinBox.setMaximum(10000000)
        self.duration_C1_spinBox.setProperty("value", 1)
        self.duration_C1_spinBox.setObjectName(_fromUtf8("duration_C1_spinBox"))
        self.horizontalLayout_20.addWidget(self.duration_C1_spinBox)
        spacerItem10 = QtGui.QSpacerItem(90, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem10)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_20)
        self.line_9 = QtGui.QFrame(self.layoutWidget)
        self.line_9.setFrameShadow(QtGui.QFrame.Plain)
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.horizontalLayout_3.addWidget(self.line_9)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.duration_C2_label = QtGui.QLabel(self.layoutWidget)
        self.duration_C2_label.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.duration_C2_label.sizePolicy().hasHeightForWidth())
        self.duration_C2_label.setSizePolicy(sizePolicy)
        self.duration_C2_label.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.duration_C2_label.setFont(font)
        self.duration_C2_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.duration_C2_label.setObjectName(_fromUtf8("duration_C2_label"))
        self.horizontalLayout_2.addWidget(self.duration_C2_label)
        self.duration_C2_spinBox = QtGui.QSpinBox(self.layoutWidget)
        self.duration_C2_spinBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.duration_C2_spinBox.sizePolicy().hasHeightForWidth())
        self.duration_C2_spinBox.setSizePolicy(sizePolicy)
        self.duration_C2_spinBox.setMinimumSize(QtCore.QSize(100, 35))
        self.duration_C2_spinBox.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.duration_C2_spinBox.setFont(font)
        self.duration_C2_spinBox.setStyleSheet(_fromUtf8("background-color: rgb(255,255,255);"))
        self.duration_C2_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.duration_C2_spinBox.setPrefix(_fromUtf8(""))
        self.duration_C2_spinBox.setMinimum(1)
        self.duration_C2_spinBox.setMaximum(10000000)
        self.duration_C2_spinBox.setProperty("value", 1)
        self.duration_C2_spinBox.setObjectName(_fromUtf8("duration_C2_spinBox"))
        self.horizontalLayout_2.addWidget(self.duration_C2_spinBox)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem11 = QtGui.QSpacerItem(59, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.line_10 = QtGui.QFrame(self.layoutWidget)
        self.line_10.setFrameShadow(QtGui.QFrame.Plain)
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.horizontalLayout_3.addWidget(self.line_10)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.duration_C3_label = QtGui.QLabel(self.layoutWidget)
        self.duration_C3_label.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.duration_C3_label.setFont(font)
        self.duration_C3_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.duration_C3_label.setObjectName(_fromUtf8("duration_C3_label"))
        self.horizontalLayout_25.addWidget(self.duration_C3_label)
        self.duration_C3_spinBox = QtGui.QSpinBox(self.layoutWidget)
        self.duration_C3_spinBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.duration_C3_spinBox.sizePolicy().hasHeightForWidth())
        self.duration_C3_spinBox.setSizePolicy(sizePolicy)
        self.duration_C3_spinBox.setMinimumSize(QtCore.QSize(100, 35))
        self.duration_C3_spinBox.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.duration_C3_spinBox.setFont(font)
        self.duration_C3_spinBox.setStyleSheet(_fromUtf8("background-color: rgb(255,255,255);"))
        self.duration_C3_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.duration_C3_spinBox.setPrefix(_fromUtf8(""))
        self.duration_C3_spinBox.setMinimum(1)
        self.duration_C3_spinBox.setMaximum(10000000)
        self.duration_C3_spinBox.setProperty("value", 1)
        self.duration_C3_spinBox.setObjectName(_fromUtf8("duration_C3_spinBox"))
        self.horizontalLayout_25.addWidget(self.duration_C3_spinBox)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_25)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem12 = QtGui.QSpacerItem(20, 100, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem12)
        self.line_13 = QtGui.QFrame(self.layoutWidget)
        self.line_13.setFrameShadow(QtGui.QFrame.Plain)
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.verticalLayout.addWidget(self.line_13)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem13)
        self.set_button = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.set_button.sizePolicy().hasHeightForWidth())
        self.set_button.setSizePolicy(sizePolicy)
        self.set_button.setMaximumSize(QtCore.QSize(150, 75))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.set_button.setFont(font)
        self.set_button.setStyleSheet(_fromUtf8("background-color: rgb(255, 191, 88);"))
        self.set_button.setObjectName(_fromUtf8("set_button"))
        self.horizontalLayout.addWidget(self.set_button)
        spacerItem14 = QtGui.QSpacerItem(40, 75, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem14)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

        self.show()

    def change_ctrl(self, ctrlnumb):
        if ctrlnumb == 1:
            if self.ctrl1_checkBox.isChecked():
                self.duration_C1_label.setEnabled(True)
                self.duration_C1_spinBox.setEnabled(True)
                self.ctrl2_checkBox.setEnabled(False)
                self.ctrl3_checkBox.setEnabled(False)
                self.aux_led_checkBox.setEnabled(False)
            else:
                self.duration_C1_label.setEnabled(False)
                self.duration_C1_spinBox.setEnabled(False)
                self.ctrl2_checkBox.setEnabled(True)
                self.ctrl3_checkBox.setEnabled(True)
                self.aux_led_checkBox.setEnabled(True)
        elif ctrlnumb == 2:
            if self.ctrl2_checkBox.isChecked():
                self.duration_C2_label.setEnabled(True)
                self.duration_C2_spinBox.setEnabled(True)
                self.ctrl1_checkBox.setEnabled(False)
                self.ctrl3_checkBox.setEnabled(False)
                self.aux_led_checkBox.setEnabled(False)
            else:
                self.duration_C2_label.setEnabled(False)
                self.duration_C2_spinBox.setEnabled(False)
                self.ctrl1_checkBox.setEnabled(True)
                self.ctrl3_checkBox.setEnabled(True)
                self.aux_led_checkBox.setEnabled(True)
        elif ctrlnumb == 3:
            if self.ctrl3_checkBox.isChecked():
                self.duration_C3_label.setEnabled(True)
                self.duration_C3_spinBox.setEnabled(True)
                self.ctrl1_checkBox.setEnabled(False)
                self.ctrl2_checkBox.setEnabled(False)
                self.aux_led_checkBox.setEnabled(False)
            else:
                self.duration_C3_label.setEnabled(False)
                self.duration_C3_spinBox.setEnabled(False)
                self.ctrl1_checkBox.setEnabled(True)
                self.ctrl2_checkBox.setEnabled(True)
                self.aux_led_checkBox.setEnabled(True)
        elif ctrlnumb == 4:
            if self.aux_led_checkBox.isChecked():
                self.duration_AL_label.setEnabled(True)
                self.duration_AL_spinBox.setEnabled(True)
                self.ctrl1_checkBox.setEnabled(False)
                self.ctrl2_checkBox.setEnabled(False)
                self.ctrl3_checkBox.setEnabled(False)
            else:
                self.duration_C3_label.setEnabled(False)
                self.duration_C3_spinBox.setEnabled(False)
                self.ctrl1_checkBox.setEnabled(True)
                self.ctrl2_checkBox.setEnabled(True)
                self.ctrl3_checkBox.setEnabled(True)

    def retranslateUi(self):
        self.setWindowTitle(_translate("self", "OSP", None))
        self.setWindowIcon(QtGui.QIcon("../Python Files/Images/logo_icon.png"))
        self.title_label.setText(_translate("self", "<html><head/><body><p align=\"center\">AUXILIARY CONTROL</p></body></html>", None))
        self.aux_led_checkBox.setText(_translate("self", "AUX LED", None))
        self.ctrl1_checkBox.setText(_translate("self", "Port 1", None))
        self.ctrl2_checkBox.setText(_translate("self", "Port 2", None))
        self.ctrl3_checkBox.setText(_translate("self", "Port 3", None))
        self.duration_AL_label.setText(_translate("self", "Duration :", None))
        self.duration_AL_spinBox.setSuffix(_translate("self", " ms", None))
        self.duration_C1_label.setText(_translate("self", "Duration :", None))
        self.duration_C1_spinBox.setSuffix(_translate("self", " ms", None))
        self.duration_C2_label.setText(_translate("self", "<html><head/><body><p align=\"center\">Duration :</p></body></html>", None))
        self.duration_C2_spinBox.setSuffix(_translate("self", " ms", None))
        self.duration_C3_label.setText(_translate("self", "<html><head/><body><p align=\"center\">Duration :</p></body></html>", None))
        self.duration_C3_spinBox.setSuffix(_translate("self", " ms", None))
        self.set_button.setText(_translate("self", "SET", None))

