# -*- coding: utf-8 -*-

# self implementation generated from reading ui file 'kineticScreen.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class kineticScreen(QtGui.QWidget):
    def __init__(self):
        super(kineticScreen, self).__init__()
        self.initUI()
        self.interval_checkBox.stateChanged.connect(lambda: self.set_kineticMode(1))
        self.repeat_checkBox.stateChanged.connect(lambda: self.set_kineticMode(2))

    def initUI(self):
        self.setObjectName(_fromUtf8("self"))
        self.resize(800, 480)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.setMaximumSize(QtCore.QSize(800, 480))
        self.setStyleSheet(_fromUtf8("background-color: rgb(97, 161, 243);"))
        self.layoutWidget = QtGui.QWidget(self)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 781, 391))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.back_button = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_button.sizePolicy().hasHeightForWidth())
        self.back_button.setSizePolicy(sizePolicy)
        self.back_button.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto"))
        font.setPointSize(14)
        self.back_button.setFont(font)
        self.back_button.setStyleSheet(_fromUtf8("background-color: rgb(255, 191, 88);"))
        self.back_button.setObjectName(_fromUtf8("back_button"))
        self.horizontalLayout_17.addWidget(self.back_button)
        spacerItem = QtGui.QSpacerItem(675, 35, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem)
        self.verticalLayout_9.addLayout(self.horizontalLayout_17)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.line_7 = QtGui.QFrame(self.layoutWidget)
        self.line_7.setFrameShadow(QtGui.QFrame.Plain)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.verticalLayout_10.addWidget(self.line_7)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.title_label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_label.sizePolicy().hasHeightForWidth())
        self.title_label.setSizePolicy(sizePolicy)
        self.title_label.setMaximumSize(QtCore.QSize(555, 40))
        self.title_label.setStyleSheet(_fromUtf8("font: 75 25pt \"Roboto\";"))
        self.title_label.setTextFormat(QtCore.Qt.AutoText)
        self.title_label.setObjectName(_fromUtf8("title_label"))
        self.horizontalLayout_2.addWidget(self.title_label)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_2)
        self.line_8 = QtGui.QFrame(self.layoutWidget)
        self.line_8.setFrameShadow(QtGui.QFrame.Plain)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.verticalLayout_10.addWidget(self.line_8)
        self.verticalLayout_9.addLayout(self.verticalLayout_10)
        spacerItem3 = QtGui.QSpacerItem(20, 53, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_9.addItem(spacerItem3)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.interval_checkBox = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.interval_checkBox.setFont(font)
        self.interval_checkBox.setStyleSheet(_fromUtf8("QCheckBox::indicator {\n"
"    width: 30px;\n"
"    height: 30px;\n"
"}"))
        self.interval_checkBox.setIconSize(QtCore.QSize(50, 50))
        self.interval_checkBox.setCheckable(True)
        self.interval_checkBox.setObjectName(_fromUtf8("interval_checkBox"))
        self.horizontalLayout_18.addWidget(self.interval_checkBox)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem4)
        self.repeat_checkBox = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.repeat_checkBox.setFont(font)
        self.repeat_checkBox.setStyleSheet(_fromUtf8("QCheckBox::indicator {\n"
"    width: 30px;\n"
"    height: 30px;\n"
"}"))
        self.repeat_checkBox.setIconSize(QtCore.QSize(50, 50))
        self.repeat_checkBox.setCheckable(True)
        self.repeat_checkBox.setObjectName(_fromUtf8("repeat_checkBox"))
        self.horizontalLayout_18.addWidget(self.repeat_checkBox)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem5)
        self.verticalLayout_9.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.duration_label = QtGui.QLabel(self.layoutWidget)
        self.duration_label.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.duration_label.setFont(font)
        self.duration_label.setAlignment(QtCore.Qt.AlignCenter)
        self.duration_label.setObjectName(_fromUtf8("duration_label"))
        self.horizontalLayout_20.addWidget(self.duration_label)
        self.duration_spinBox = QtGui.QSpinBox(self.layoutWidget)
        self.duration_spinBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.duration_spinBox.sizePolicy().hasHeightForWidth())
        self.duration_spinBox.setSizePolicy(sizePolicy)
        self.duration_spinBox.setMinimumSize(QtCore.QSize(0, 35))
        self.duration_spinBox.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.duration_spinBox.setFont(font)
        self.duration_spinBox.setStyleSheet(_fromUtf8("background-color: rgb(255,255,255);"))
        self.duration_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.duration_spinBox.setPrefix(_fromUtf8(""))
        self.duration_spinBox.setMinimum(1)
        self.duration_spinBox.setMaximum(10000000)
        self.duration_spinBox.setProperty("value", 1)
        self.duration_spinBox.setObjectName(_fromUtf8("duration_spinBox"))
        self.horizontalLayout_20.addWidget(self.duration_spinBox)
        self.verticalLayout_11.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.timeInterval_label = QtGui.QLabel(self.layoutWidget)
        self.timeInterval_label.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.timeInterval_label.setFont(font)
        self.timeInterval_label.setObjectName(_fromUtf8("timeInterval_label"))
        self.horizontalLayout_21.addWidget(self.timeInterval_label)
        self.timeInterval_spinBox = QtGui.QSpinBox(self.layoutWidget)
        self.timeInterval_spinBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeInterval_spinBox.sizePolicy().hasHeightForWidth())
        self.timeInterval_spinBox.setSizePolicy(sizePolicy)
        self.timeInterval_spinBox.setMinimumSize(QtCore.QSize(0, 35))
        self.timeInterval_spinBox.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.timeInterval_spinBox.setFont(font)
        self.timeInterval_spinBox.setStyleSheet(_fromUtf8("background-color: rgb(255,255,255);"))
        self.timeInterval_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.timeInterval_spinBox.setPrefix(_fromUtf8(""))
        self.timeInterval_spinBox.setMinimum(1)
        self.timeInterval_spinBox.setMaximum(1000000)
        self.timeInterval_spinBox.setProperty("value", 1)
        self.timeInterval_spinBox.setObjectName(_fromUtf8("timeInterval_spinBox"))
        self.horizontalLayout_21.addWidget(self.timeInterval_spinBox)
        self.verticalLayout_11.addLayout(self.horizontalLayout_21)
        spacerItem6 = QtGui.QSpacerItem(20, 53, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_11.addItem(spacerItem6)
        self.horizontalLayout_19.addLayout(self.verticalLayout_11)
        self.line_9 = QtGui.QFrame(self.layoutWidget)
        self.line_9.setFrameShadow(QtGui.QFrame.Plain)
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.horizontalLayout_19.addWidget(self.line_9)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.numbRepeats_label = QtGui.QLabel(self.layoutWidget)
        self.numbRepeats_label.setEnabled(False)
        self.numbRepeats_label.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.numbRepeats_label.setFont(font)
        self.numbRepeats_label.setObjectName(_fromUtf8("numbRepeats_label"))
        self.horizontalLayout_22.addWidget(self.numbRepeats_label)
        self.numbRepeats_spinBox = QtGui.QSpinBox(self.layoutWidget)
        self.numbRepeats_spinBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(45)
        sizePolicy.setHeightForWidth(self.numbRepeats_spinBox.sizePolicy().hasHeightForWidth())
        self.numbRepeats_spinBox.setSizePolicy(sizePolicy)
        self.numbRepeats_spinBox.setMinimumSize(QtCore.QSize(0, 35))
        self.numbRepeats_spinBox.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.numbRepeats_spinBox.setFont(font)
        self.numbRepeats_spinBox.setStyleSheet(_fromUtf8("background-color: rgb(255,255,255);"))
        self.numbRepeats_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.numbRepeats_spinBox.setSuffix(_fromUtf8(""))
        self.numbRepeats_spinBox.setPrefix(_fromUtf8(""))
        self.numbRepeats_spinBox.setMinimum(1)
        self.numbRepeats_spinBox.setMaximum(10000)
        self.numbRepeats_spinBox.setObjectName(_fromUtf8("numbRepeats_spinBox"))
        self.horizontalLayout_22.addWidget(self.numbRepeats_spinBox)
        self.verticalLayout_12.addLayout(self.horizontalLayout_22)
        spacerItem7 = QtGui.QSpacerItem(20, 85, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_12.addItem(spacerItem7)
        self.horizontalLayout_19.addLayout(self.verticalLayout_12)
        self.verticalLayout_9.addLayout(self.horizontalLayout_19)
        spacerItem8 = QtGui.QSpacerItem(20, 53, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_9.addItem(spacerItem8)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.set_button = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.set_button.sizePolicy().hasHeightForWidth())
        self.set_button.setSizePolicy(sizePolicy)
        self.set_button.setMaximumSize(QtCore.QSize(100, 75))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.set_button.setFont(font)
        self.set_button.setStyleSheet(_fromUtf8("background-color: rgb(255, 191, 88);"))
        self.set_button.setObjectName(_fromUtf8("set_button"))
        self.horizontalLayout.addWidget(self.set_button)
        spacerItem10 = QtGui.QSpacerItem(40, 75, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.verticalLayout_9.addLayout(self.horizontalLayout)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

        self.show()

    def set_kineticMode(self, mode):
        if mode == 1:
            if self.interval_checkBox.isChecked():
                self.timeInterval_spinBox.setEnabled(True)
                self.timeInterval_label.setEnabled(True)
                self.duration_spinBox.setEnabled(True)
                self.duration_label.setEnabled(True)
                self.repeat_checkBox.setEnabled(False)
                self.numbRepeats_spinBox.setEnabled(False)
                self.numbRepeats_label.setEnabled(False)
            else:
                self.timeInterval_spinBox.setEnabled(False)
                self.timeInterval_label.setEnabled(False)
                self.duration_spinBox.setEnabled(False)
                self.duration_label.setEnabled(False)
                self.repeat_checkBox.setEnabled(True)
                self.numbRepeats_spinBox.setEnabled(False)
                self.numbRepeats_label.setEnabled(False)
        elif mode == 2:
            if self.repeat_checkBox.isChecked():
                self.numbRepeats_spinBox.setEnabled(True)
                self.numbRepeats_label.setEnabled(True)
                self.interval_checkBox.setEnabled(False)
                self.timeInterval_spinBox.setEnabled(False)
                self.timeInterval_label.setEnabled(False)
                self.duration_spinBox.setEnabled(False)
                self.duration_label.setEnabled(False)
            else:
                self.interval_checkBox.setEnabled(True)
                self.timeInterval_spinBox.setEnabled(False)
                self.timeInterval_label.setEnabled(False)
                self.numbRepeats_spinBox.setEnabled(False)
                self.numbRepeats_label.setEnabled(False)
                self.duration_spinBox.setEnabled(False)
                self.duration_label.setEnabled(False)

    def retranslateUi(self):
        self.setWindowTitle(_translate("self", "OSP", None))
        self.setWindowIcon(QtGui.QIcon("../Python Files/Images/logo_icon.png"))
        self.back_button.setText(_translate("self", "Back", None))
        self.title_label.setText(_translate("self", "<html><head/><body><p align=\"center\">KINETIC SETTINGS</p></body></html>", None))
        self.interval_checkBox.setText(_translate("self", "Interval", None))
        self.repeat_checkBox.setText(_translate("self", "Repeat", None))
        self.duration_label.setText(_translate("self", "Duration :", None))
        self.duration_spinBox.setSuffix(_translate("self", " ms", None))
        self.timeInterval_label.setText(_translate("self", "<html><head/><body><p align=\"center\">Time Interval :</p></body></html>", None))
        self.timeInterval_spinBox.setSuffix(_translate("self", " ms", None))
        self.numbRepeats_label.setText(_translate("self", "Number of Repeats :", None))
        self.set_button.setText(_translate("self", "SET", None))

